import Navbar from "../../components/layout/Navbar";
import Footer from "../../components/home/Footer";

export default function ReportPage() {
  return (
    <>
      <Navbar />

      <main className="min-h-screen bg-gradient-to-b from-slate-950 via-black to-slate-950 pt-32 text-white">

        <div className="mx-auto max-w-5xl px-6">

          <div className="rounded-3xl border border-white/10 bg-white/5 p-10">

            <h1 className="text-5xl font-black">
              AI Screening Report
            </h1>

            <p className="mt-3 text-slate-400">
              Generated by Kāyaanah Vision
            </p>

            <div className="mt-12 grid gap-6 md:grid-cols-2">

              <Card title="Patient">
                Anonymous User
              </Card>

              <Card title="Disease">
                Psoriasis
              </Card>

              <Card title="Confidence">
                98.2%
              </Card>

              <Card title="Risk Level">
                High
              </Card>

              <Card title="Model">
                EfficientNet-B4 + Transformer
              </Card>

              <Card title="Status">
                AI Screening Complete
              </Card>

            </div>

            <div className="mt-10 rounded-2xl bg-cyan-500/10 p-8">

              <h2 className="text-2xl font-bold text-cyan-400">
                Recommendation
              </h2>

              <p className="mt-4 leading-8 text-slate-300">

                The uploaded image shows characteristics
                commonly associated with psoriasis.
                Please consult a qualified dermatologist
                for clinical examination and confirmation.

              </p>

            </div>

            <div className="mt-10 flex flex-wrap gap-4">

              <button className="rounded-xl bg-cyan-500 px-8 py-4 font-semibold text-black">
                Download PDF
              </button>

              <button className="rounded-xl border border-white/20 px-8 py-4">
                Analyze Another Image
              </button>

            </div>

          </div>

        </div>

      </main>

      <Footer />

    </>
  );
}

function Card({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-2xl bg-black/30 p-6">

      <p className="text-sm text-slate-400">
        {title}
      </p>

      <h3 className="mt-2 text-2xl font-bold">
        {children}
      </h3>

    </div>
  );
}